-- 코드를 작성해주세요
SELECT SUM(HR_GRADE.SCORE) AS SCORE, HR_EMPLOYEES.EMP_NO, HR_EMPLOYEES.EMP_NAME, HR_EMPLOYEES.POSITION, HR_EMPLOYEES.EMAIL 
FROM HR_EMPLOYEES 
JOIN HR_GRADE 
ON HR_GRADE.EMP_NO = HR_EMPLOYEES.EMP_NO 
GROUP BY HR_GRADE.YEAR, HR_GRADE.EMP_NO
ORDER BY SUM(HR_GRADE.SCORE) DESC
LIMIT 1
;